language: python

cache:
  directories:
    - $HOME/.cache/pip

os:
    - linux

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

env:
  global:
    - PYTHON_UNITTEST=true

install: pip install -r requirements.txt
script: python installDependencies.py && python runAllTests.py test
branches:
    only:
    - master
    - development
    - /^issue-.*$/
