# WALKOFF Stack file for Windows.
# Currently the proper bootloader only supports Linux, support for other OSes will come at a later date.
# In the meantime, you will need to manually edit this file to modify the Walkoff stack.

version: '3.5'

services:

  # WALKOFF Resources - third-party dependencies

  resource_registry:
    image: registry:2
    networks:
      - walkoff_default
    deploy:
      placement:
        constraints: [node.role==manager]
    ports:
      - 5000:5000

#    The commented lines are needed to enable auth on the custom registry
#    environment:
#      - REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
#      - REGISTRY_HTTP_TLS_KEY: /certs/domain.key
#      - REGISTRY_AUTH: htpasswd
#      - REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
#      - REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - .\data\registry:/var/lib/registry
#      - ./data/config.yml:/etc/docker/registry/config.yml
#      - /var/lib/boot2docker:/certs
#      - /var/lib/boot2docker/auth:/auth

  resource_redis:
    image: "redis"
    networks:
      - walkoff_default
#    ports:
#      - "6379:6379"
    command: redis-server --port 6379
#    volumes:
#      - /path/to/persistent/dir/redis:/data

  resource_minio:
    image: minio/minio
    networks:
      - walkoff_default
#    ports:
#      - "9001:9000"
    volumes:
#      - data1:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - .\apps:/app/apps
    deploy:
      placement:
        constraints: [node.role==manager]
    environment:
      MINIO_ACCESS_KEY: walkoff
      MINIO_SECRET_KEY: walkoff123
    command: server /data

  resource_postgres:
    image: "postgres"
    networks:
      - walkoff_default
    environment:
      - "POSTGRES_USER=walkoff"
      - "POSTGRES_PASSWORD=walkoff"
    deploy:
      placement:
        constraints: [node.role==manager]
    volumes:
      - walkoff_pgdata:/var/lib/postgresql/data

  resource_portainer:
    image: "portainer/portainer"
    networks:
      - walkoff_default
    deploy:
      placement:
        constraints: [node.role==manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .\data\portainer:/data


  # WALKOFF Core components

  resource_nginx:
    depends_on:
    - core_api_gateway
    image: bitnami/nginx:latest
    networks:
    - walkoff_default
    ports:
    - 8080:8080
    volumes:
    - .\nginx\walkoff.conf:/opt/bitnami/nginx/conf/server_blocks/walkoff.conf:ro
    - .\nginx\cert.pem:/opt/bitnami/nginx/conf/cert.pem:ro
    - .\nginx\key.pem:/opt/bitnami/nginx/conf/key.pem:ro

  core_api_gateway:
    build:
      context: ./
      dockerfile: ./api_gateway/Dockerfile
    configs:
    - common_env.yml
    depends_on:
    - resource_redis
    - resource_postgres
    image: 127.0.0.1:5000/api_gateway:latest
    networks:
    - walkoff_default
    secrets:
    - walkoff_encryption_key
    - walkoff_internal_key
#    volumes:
#    - .\api_gateway\client\dist\walkoff:/app/api_gateway/client/dist/walkoff

  core_umpire:
    build:
      context: ./
      dockerfile: umpire/Dockerfile
    configs:
    - common_env.yml
    depends_on:
    - resource_redis
    - resource_registry
    - resource_minio
    deploy:
      placement:
        constraints:
        - node.role==manager
    image: 127.0.0.1:5000/umpire:latest
    networks:
    - walkoff_default
    secrets:
    - walkoff_encryption_key
    - walkoff_internal_key
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./apps:/app/apps

  core_worker:
    build:
      context: ./
      dockerfile: ./worker/Dockerfile
    configs:
    - common_env.yml
    secrets:
    - walkoff_encryption_key
    - walkoff_internal_key
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none
    image: 127.0.0.1:5000/worker:latest
    networks:
    - walkoff_default


  # WALKOFF App services

  app_hello_world:
    build:
      context: apps/hello_world/1.0.0
      dockerfile: Dockerfile
    configs:
      - common_env.yml
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none
    environment:
      - APP_NAME=hello_world
    image: 127.0.0.1:5000/walkoff_app_hello_world:1.0.0
    networks:
      - walkoff_default
    secrets:
      - walkoff_encryption_key
    volumes:
      - .\data\shared:/app/shared
  app_hive:
    build:
      context: apps/hive/1.0.0
      dockerfile: Dockerfile
    configs:
      - common_env.yml
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none
    environment:
      - APP_NAME=hive
    image: 127.0.0.1:5000/walkoff_app_hive:1.0.0
    networks:
      - walkoff_default
    secrets:
      - walkoff_encryption_key
    volumes:
      - .\data\shared:/app/shared
  app_ip_addr_utils:
    build:
      context: apps/ip_addr_utils/1.0.0
      dockerfile: Dockerfile
    configs:
      - common_env.yml
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none
    environment:
      - APP_NAME=ip_addr_utils
    image: 127.0.0.1:5000/walkoff_app_ip_addr_utils:1.0.0
    networks:
      - walkoff_default
    secrets:
      - walkoff_encryption_key
    volumes:
      - .\data\shared:/app/shared
  app_nmap:
    build:
      context: apps/nmap/1.0.0
      dockerfile: Dockerfile
    configs:
      - common_env.yml
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none
    environment:
      - APP_NAME=nmap
    image: 127.0.0.1:5000/walkoff_app_nmap:1.0.0
    networks:
      - walkoff_default
    secrets:
      - walkoff_encryption_key
    volumes:
      - .\data\shared:/app/shared
  app_power_shell:
    build:
      context: apps/power_shell/1.0.0
      dockerfile: Dockerfile
    configs:
      - common_env.yml
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none
    environment:
      - APP_NAME=power_shell
    image: 127.0.0.1:5000/walkoff_app_power_shell:1.0.0
    networks:
      - walkoff_default
    secrets:
      - walkoff_encryption_key
    volumes:
      - .\data\shared:/app/shared
  app_sdk:
    build:
      context: ./
      dockerfile: ./app_sdk/Dockerfile
    configs:
      - common_env.yml
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none
    image: 127.0.0.1:5000/walkoff_app_sdk:latest
    networks:
      - walkoff_default
  app_ssh:
    build:
      context: apps/ssh/1.0.0
      dockerfile: Dockerfile
    configs:
      - common_env.yml
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none
    environment:
      - APP_NAME=ssh
    image: 127.0.0.1:5000/walkoff_app_ssh:1.0.0
    networks:
      - walkoff_default
    secrets:
      - walkoff_encryption_key
    volumes:
      - .\data\shared:/app/shared
  app_walk_off:
    build:
      context: apps/walk_off/1.0.0
      dockerfile: Dockerfile
    configs:
      - common_env.yml
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none
    environment:
      - APP_NAME=walk_off
    image: 127.0.0.1:5000/walkoff_app_walk_off:1.0.0
    networks:
      - walkoff_default
    secrets:
      - walkoff_encryption_key
    volumes:
      - .\data\shared:/app/shared

configs:
  common_env.yml:
    file: .\data\config.yml

networks:
  walkoff_default:
    external: true

secrets:
  walkoff_encryption_key:
    external: true
  walkoff_internal_key:
    external: true

volumes:
  walkoff_pgdata:
    external: true