swagger: "2.0"
info:
  version: "1.0.0"
  title: "Count"
  description: "A flag that performs comparision operations on objects"
  contact:
    name: "Walkoff Team"
  license:
    name: "Creative Commons"
schemes:
  - "walkoff"
paths:
  count:
    run:
      operationId: execute
      description: "Conditional that compares the value of an input"
      produces:
        - "text/plain"
      parameters:
          - name: "type"
            in: "query"
            description: "type of object to compare"
            required: true
            type: "string"

          - name: "threshold"
            in: "query"
            description: "threshold to compare against"
            required: true
            type: "integer"
            format: "int32"

          - name: "operator"
            in: "query"
            description: "comparison type"
            required: true
            type: "string"

          - name: "value"
            in: "query"
            description: "the input"
            required: true
            type: "string"
      responses:
        "200":
          description: "result"
          schema:
            type: "string"
