swagger: "2.0"
info:
  version: "1.0.0"
  title: "Regular Expression Match"
  description: "Matches the input using a regular expression matcher. See data/functions.json for argument information"
  contact:
    name: "Walkoff Team"
  license:
    name: "Creative Commons"
schemes:
  - "walkoff"
paths:
  regMatch:
    run:
      operationId: execute
      description: "Conditional that compares the value of an input"
      produces:
        - "text/plain"
      parameters:
          - name: "regex"
            in: "query"
            description: "the regex to match the value against"
            required: true
            type: "string"

          - name: "value"
            in: "query"
            description: "the input"
            required: true
            type: "string"
      responses:
        "200":
          description: "result"
          schema:
            type: "string"
